### ISSUE TITLE
Image takes 1 minutes to show

### ISSUE THREAD

**Issue by 0x6f6868656c6c6e6f** [NyarchLinux/CatgirlDownloader#2]
Hello,

When launching the app or just trying to request a new image I get a loading animation for a full minute before the image is displayed. It is a consistent timing, but the image had already been chosen, as I can get the link to the image before it is finished showing.
I am using the flatpak provided for release 0.2.5 and this is the only log that I am getting:
```
$ flatpak run moe.nyarchlinux.catgirldownloader
/home/emneo/.var/app/moe.nyarchlinux.catgirldownloader/config
```

I am running an updated Nobara Linux 38.

![image](https://github.com/NyarchLinux/CatgirlDownloader/assets/151401415/bc365c4d-9862-4720-8ec6-f0213247f24f)

**Comment by FrancescoCaracciolo** [comment]
This is pretty weird since nothing like this happens on any of my systems. May it be some connection issue on your end?

**Comment by FrancescoCaracciolo** [comment]
Looks like a connection problem
